### ISSUE TITLE
gsettings keys and interfaces

### ISSUE THREAD

**Issue by johanmalm** [qtilities/gtk-conf#1]
Regarding `Settings.cpp`

1. It looks like the `gsettings` keys are different to those in the `.ini` files.

In a terminal, use `gsettings list-schemas` and then for example `gsettings list-keys org.gnome.desktop.interface`
For example, you can get `gtk-theme` with `gsettings get org.gnome.desktop.interface gtk-theme`.

2. It looks like there are different schemas to cover the settings in the `gtk_conf()`, for example: `org.gnome.desktop.sound`. I didn't realise that because I've only ever played with gtk/icon/cursor themes :smile:

3. Maybe the best approach is to create private variables like `gsettings_desktop_sound_`, etc.

4. We might need to free the gsettings object(s) in the destructore. Not sure if it's `g_free()`, `g_object_unref()` or other. Might be worth running with ASAN for that.

**Comment by redtide** [comment]
> Regarding `Settings.cpp`
> 
> 1. It looks like the `gsettings` keys are different to those in the `.ini` files.

It's a bit of confusion in GTK, because we need to work with GtkSettings, that I wasn't able to make it work, which has those naming convention, but it's not clear where it's used other than .ini files; these should be only a last resort for gsettings, which in turn seems to use the naming convention of Gio.Settings instead. Or do we miss a new tool that uses the same settings.ini naming?

> It looks like there are different schemas to cover the settings in the gtk_conf(), for example: org.gnome.desktop.sound. I didn't realise that because I've only ever played with gtk/icon/cursor themes 😄

Same! And now there is also private, for recent files...

> Maybe the best approach is to create private variables like gsettings_desktop_sound_, etc.

Don't you like the camel case fashion? 😄 

> We might need to free the gsettings object(s) in the destructore. Not sure if it's g_free(), g_object_unref() or other. Might be worth running with ASAN for that.

Haven't tested but I guess `g_object_unref()` should be fine, but we will know soon :)

**Comment by redtide** [comment]
I just pushed a commit that should make gsettings work, I'm not sure what to do with the other commented settings, maybe we should use a mix of settings.ini to cover all possibilities, unless we get how to make work GtkSettings.

I added a todo file, I wonder if there is a way to make a watcher (I guess a gsignal somewhere) to add some alert about changed settings from another editor, to tell the user if he wants to save the current or update to restore/reset to the changed valued made elsewhere.

Some suggestion about other features/missing stuff, apart the missing options?

**Comment by johanmalm** [comment]
> I just pushed a commit that should make gsettings work, I'm not sure what to do with the other commented settings, maybe we should use a mix of settings.ini to cover all possibilities, unless we get how to make work GtkSettings.

I'm not sure. Looks like there are more settings supported by `GtkSettings` compared with `gsettings`. Maybe I said the wrong thing before about preferring `gsettings`.

`gtk-conf` works really well now. I love the way GTK applications update the moment you press "save". 

> I added a todo file, I wonder if there is a way to make a watcher (I guess a gsignal somewhere) to add some alert about changed settings from another editor, to tell the user if he wants to save the current or update to restore/reset to the changed valued made elsewhere.

Looks like this one: https://docs.gtk.org/gio/signal.Settings.changed.html ... with `g_signal_connect()` I suppose.

> Some suggestion about other features/missing stuff, apart the missing options?

Will have a look.

**Comment by johanmalm** [comment]
The tooltip is great. I've been thinking about doing that `labwc-tweaks` too.

What does the `prefer-dark-theme` actually do? Is it application specific? Is it a global settings to ask all GTK applications to use the `-dark` variant of the current theme if one exists?

On the theme stack, consider:

- [x] Deleting "System" and calling the first combobox `Gtk theme`.
- [x] Similarly `s/Icons/Icon theme/`
- [x] `s/Cursor/Cursor theme/` (because we then have `Cursor size` so seems inconsistent.

I wonder if the `Antialiasing` and `Hinting` for xft is old technology that we should expose to users anymore in a settings client like this. In fact, the same could possibly be said for all the items on the 'font' stack except the last one.

Clicking on the 'font-selector' results in a crash for me (`QObject::connect(QObject, QGtk2Dialog): invalid nullptr parameter`)

Should we have a HiDPI stack. The environment variables `GDK_SCALE` and `GDK_DPI_SCALE` seem important to GTK applications, but there might be a gsettings key for this too. Not sure. Otherwise we could consider settings those in `labwc-tweaks`.

How about these: 

```
$ gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "[{'Gdk/WindowScalingFactor', <2>}]"
$ gsettings set org.gnome.desktop.interface scaling-factor 2
$ gsettings set org.gnome.desktop.interface text-scaling-factor 1.5
```

It might be worth opening `gnome-tweaks` and `gnome-control-center` to see if they have any other interesting options worth considering. I've got them on my Ubuntu partition, so can't look now.

**Comment by johanmalm** [comment]
Assume LXQt use `foo_` rather than `mFoo` or `m_foo` for private variables?

Should we add `_` to `guiSettings`, etc?

Consider calling `load()` from the Settings constructor rather than `DialogMain.cpp +29`

Suggest refactoring `DialogMain::findThemes()` to avoid `searchWhat` and `searchWhat2`. I did something similar in `labwc-tweaks` (one function/method to find all types of themes), but I think it's easier to maintain/understand if they were split into three separate methods (one for cursor themes, one of icons and one for gtk-theme).

Could we just add `$HOME/.themes` to `paths` right at the start of the method to avoid separate handling of that case later?

Suggest sorting the themes. They're currently not sorted in the combos.

**Comment by redtide** [comment]
> I'm not sure. Looks like there are more settings supported by GtkSettings compared with gsettings. Maybe I said the wrong thing before about preferring gsettings.

TBH I have no preference if it can cover the ones I use now

> gtk-conf works really well now. I love the way GTK applications update the moment you press "save".

Great! I haven't tested now against the system yet, only that the changes was reflected on DConf.

> The tooltip is great. I've been thinking about doing that labwc-tweaks too.

We can subdivide some work to make that quickly, it's trivial using just h3 and p tags but a bit boring to cover all settings. Are there texts that we can copy from?

> What does the prefer-dark-theme actually do? Is it application specific? Is it a global settings to ask all GTK applications to use the -dark variant of the current theme if one exists?

It should be like that, using a dark version if present and AFAIK it's a global setting.
I use dark themes on both GTK (Adwaita-dark) and Qt (Fusion now has also a dark mode).
Maybe there is also a possibility to use dark/light themes only for specified single apps using an env var, but I haven't tried.

The disabled one in the UI comes from GtkSettings, which looks to me better by having a single checkbox instead 3 choices (what a default setting should do when a UI aspect should be decided by the user? Just enable it or not).

I guess we could delete it together with the other that was already replaced (I disabled them in UI and commented in code). I wanted to keep it until I was sure we were not try to use GtkSettings instead GSettings.

> On the theme stack, consider: ...

I was keeping them in the Theme context (system theme, icons theme...) to have less redundancy and less space used, but I changed it as you say, it looks better.

> I wonder if the Antialiasing and Hinting for xft is old technology that we should expose to users anymore in a settings client like this. In fact, the same could possibly be said for all the items on the 'font' stack except the last one.

No preference about this, i'm not using them, they was part of lxappearance which was my initial reference, but still part of GtkSettings v4.

> Clicking on the 'font-selector' results in a crash for me (QObject::connect(QObject, QGtk2Dialog): invalid nullptr parameter)

on the FontButton? QGtk2Dialog? This sound strange, maybe you meant QDialog?
I've taken that class from LXQt LibFm, no issue here until now.
Steps to reproduce?

> Should we have a HiDPI stack. The environment variables GDK_SCALE and GDK_DPI_SCALE seem important to GTK applications, but there might be a gsettings key for this too. Not sure. Otherwise we could consider settings those in labwc-tweaks.

I use only the env vars, if we will mix with settings.ini why not using the envars? I'm about also changing my mind about an app that can set all (GTK, Qt and labwc), but there should be some reference. like you said where to draw the line.

> How about these:

No idea, I'll do some test here too, here the envvars I use:
![immagine](https://github.com/qtilities/gtk-conf/assets/1171962/9f8b7145-d2e1-4fc3-b941-346bea47e014)

EDIT: I see `scaling-factor` and `text-scaling-factor` which are both set to 1, I guess they represent `GDK_SCALE`, integer value, and `GDK_DPI_SCALE` which is float like in Qt but only for text.

**Comment by redtide** [comment]
> Assume LXQt use foo_ rather than mFoo or m_foo for private variables?

I use foo_, LXQt AFAIK use mFoo.

> Should we add _ to guiSettings, etc?

- [x] OK

> Consider calling load() from the Settings constructor rather than DialogMain.cpp +29

- [x] OK

> Suggest refactoring DialogMain::findThemes() to avoid searchWhat and searchWhat2. I did something similar in labwc-tweaks (one function/method to find all types of themes), but I think it's easier to maintain/understand if they were split into three separate methods (one for cursor themes, one of icons and one for gtk-theme).

- [x] They were 2 identical functions, I reduced to 1 instead adding another. ATM IDK how to avoid the 2 searchWhat (renemed to "searchFilter" and "searchFilter2").

> Could we just add $HOME/.themes to paths right at the start of the method to avoid separate handling of that case later?

- [x] done.

> Suggest sorting the themes. They're currently not sorted in the combos.

- [x] OK! Thank you for the advises, will fix them tomorrow.

Should be better now, I also added a Sound sections, though probably the "allow volume above 100%" should be removed.

Looks like GSettings stuff is old compared to GtkSettings and its deprecated properties (in v3). Would you like to give it a try? As said I get a nullptr but I tried only with [gtk_settings_get_default](https://docs.gtk.org/gtk4/type_func.Settings.get_default.html).

BTW GSettings seems not working for some properties here and if I remove all settings.ini there is no way at least to change the icon theme.

**Comment by johanmalm** [comment]
Running out of time today. Have compiled though and it looks really good.
 
Tried with prefer-dark, but couldn't verify if GtkSettings works.
Should we update both gtk-3.0/settings.ini and the 4.0 equivalent?

**Comment by redtide** [comment]
If we go the QSettings way I used in the beginning yes, but we should probably take into account of the differences and decide how to handle the differences, like keeping deprecated properties or not.
Otherwise using GtkSettings API, but is it possible to link and use both gtk3 and 4 libraries at same time?

**Comment by johanmalm** [comment]
My “personal” preference is gsettings because it (a) covers the settings that I’m interested in; (b) updates clients instantly; and (c) seems to be agnostic of gtk version.

It’s a dilemma though, because it only takes one variable (like prefer-dark) for us to need to to try handle GtkSettings.

It might be worth reaching out on the Grk forums to get some expert advice on this. We might be missing something.

**Comment by redtide** [comment]
> (a) covers the settings that I’m interested in

OK, can we try to use both with a "settings option setting"? 😄

> (b) updates clients instantly

not here and in some cases even no effect

> (c) seems to be agnostic of gtk version.

This is a complete mess from my POV, looks like that GSettings is an old version that they would like to replace or something (it uses stuff deprecated in gtk settings).

I think we should make a table with both version and see what works for you and what for me, at least to see where the problem is, this shouldn't happen, so we surely miss something.

Anyway... I got Gtk settings to work I think, seems like it needed gtk_init() which I didn't notice before in the docs.

**Comment by redtide** [comment]
From gtk4 docs:

>GtkSettings provides a mechanism to share global settings between applications.
>
>On the X window system, this sharing is realized by an [XSettings](http://www.freedesktop.org/wiki/Specifications/xsettings-spec) manager that is usually part of the desktop environment, along with utilities that let the user change these settings.

I have no idea if and how these works, but looks like it's not my case

>On Wayland, the settings are obtained either via a settings portal, or by reading desktop settings from DConf.

this is yours, but we need to know why they are using GSettings instead GtkSettings (for consistency).

>On macOS, the settings are obtained from NSUserDefaults.
>
>In the absence of these sharing mechanisms, GTK reads default values for settings from settings.ini files in /etc/gtk-4.0, $XDG_CONFIG_DIRS/gtk-4.0 and $XDG_CONFIG_HOME/gtk-4.0.

This might be my case, after testing some properties in DConf seems not having any impact.

So it seems I could use GSettings on Wayland (DConf) and GtkSettings on X11.

2 things:

> EDIT: I see scaling-factor and text-scaling-factor which are both set to 1, I guess they represent GDK_SCALE, integer value, and GDK_DPI_SCALE which is float like in Qt but only for text.

are these 2 settings working for you and so replacing the env vars?

If you have DConf installed, have you only 4 settings? Do you think we can get rid of allow volume above 100%?
